language: go

go:
  - 1.1.1

script:
  - go get github.com/dustin/go-jsonpointer
  - ./gen_ops_tests.py
  - go test -v ./...
  - go vet ./...

notifications:
  email:
    - dustin@couchbase.com
    - steve@couchbase.com
